diarytask/diarytask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tasks.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diarytask/tasks/urls.py
from django.urls import path, re_path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('web/', views.web, name='web'),
    path('games/', views.games, name='games'),
    path('scripts/', views.scripts, name='scripts'),
    path('another/', views.another, name='another'),
    path('<int:pk>/', views.detail, name='detail'),
    re_path('create/', views.create_new_project, name='create_new_project'),
]

diarytask/tasks/models.py
from django.db import models


class Category(models.Model):
    """ Категории проектов """
    title = models.CharField('Категория', max_length=150)
    objects = models.Manager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Language(models.Model):
    name = models.CharField('Используемый язык', max_length=50)
    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Используемый язык'
        verbose_name_plural = 'Используемые языки'


class Project(models.Model):
    """Класс проекта"""
    title = models.CharField('Название проекта', max_length=150)
    task = models.TextField('Техническое задание', blank=True)
    pub_date = models.DateTimeField('Дата публикации', null=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    upload = models.FileField('Готовый проект', upload_to='CompletedProjects/', blank=True,)
    language = models.ForeignKey(Language, verbose_name='Используемый язык', on_delete=models.SET_NULL, null=True)
    objects = models.Manager()


    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ['category']
    
    def __str__(self):
        return self.title

diarytask/tasks/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'category', 'task', 'language']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'language': forms.Select(attrs={'class': 'form-control'}),
            'task': forms.Textarea(attrs={'class': 'form-control'}),
        }


class UploadForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['upload']


class AddTask(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['task']
        

diarytask/tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from .models import Project, Category
from .forms import AddTask, ProjectForm, UploadForm
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone



def index(request):
    latest_projects_list = Project.objects.order_by('-pub_date')
    return render(request, 'index.html', {'latest_projects_list': latest_projects_list})

def web(request):
    pw = Project.objects.filter(category_id = 1)
    return render(request, 'web.html', {'web_projects': pw})

def games(request):
    pw = Project.objects.filter(category_id = 2)
    return render(request, 'games.html', {'games_projects': pw})

def scripts(request):
    pw = Project.objects.filter(category_id = 3)
    return render(request, 'scripts.html', {'scripts_projects': pw})

def another(request):
    pw = Project.objects.filter(category_id = 4)
    return render(request, 'another.html', {'another_projects': pw})

def detail(request, pk):
    p = get_object_or_404(Project, pk=pk)
    form = UploadForm(request.POST)
    project = Project.objects.get(pk__iexact=pk)
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES, instance=project)        
        if form.is_valid():
            form.save()          
    return render(request, 'detail.html', {'projects': p, 'form': form, 'project': project})

# def add_task(request, pk):
#     form_add = AddTask(request.POST)
#     pt = Project.objects.get(pk__iexact=pk)
#     if request.method == 'POST':
#         form_add = AddTask(request.POST, instance=pt)
        
#         if form_add.is_valid():
#             form_add.save() 
#         else:
#             form_add = AddTask()
#     return render(request, 'detail.html', {'form_add': form_add, 'pt': pt})

def create_new_project(request):
    form = ProjectForm(request.POST)
    project = Project()
    if request.method == 'POST':
        if form.is_valid():
            project = form.save(commit=False)
            project.pub_date = timezone.now()
            project.save()
            return redirect('tasks:detail', pk=project.pk)
        else:
            form = ProjectForm()
    return render(request, 'create.html', {'form': form})

def search(request):
    search_query = request.GET.get('search', '')
    if search_query:
        projects = Project.objects.filter(title__icontains = search_query)
    else:
        projects = Project.objects.all()
    return render(request, 'search.html', {'search_list': projects})

diarytask/templates/another.html
{% extends 'base.html' %}

{% block title %}
    Another
{% endblock %}

{% block another %}

<div class="section">
    <div class="container category-main">
        <div class="row">
            <div class="col-lg-6 offset-3 category-projects">
                <div class="text-center category-pr">
                    {% for pw in another_projects %}
                        <a href="{% url 'tasks:detail' pw.pk %}">{{pw.title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

diarytask/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block links %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/glyphicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body>
{% block header %}

<div class="section header-section">
    <div class="container container_1">
        <div class="row">
            <div class="col-lg-4">
                <a class="btn btn-primary home-button" href="{% url 'tasks:index' %}" role="button">Home</a>
            </div>
            <div class="col-lg-4">
                <a class="btn btn-primary create-button" href="{% url 'tasks:create_new_project' %}" role="button">Create new project</a>
            </div>
            <div class="col-lg-4">
                <div class="form">
                    <form action="{% url 'tasks:search' %}" class="search-form">
                        <input type="text" class="form-control search-poly" placeholder="Search" name="search">
                        <button class="btn-primary search-button" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

{% block search %}{% endblock %}
{% block web %}{% endblock %}
{% block games %}{% endblock %}
{% block scripts %}{% endblock %}
{% block another %}{% endblock %}
{% block task %}{% endblock %}
{% block form_create %}{% endblock %}
{% block project_create %}{% endblock %}


</body>
</html>

diarytask/templates/create copy.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Создание нового проекта{% endblock %}</title>
</head>
<body>
    
    {% block form_create %}
    
    <div class="row main_create">
        <div class="col-lg-6 offset-lg-3">
            <form action="create()" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="title-text">Введите название проекта</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="category" class="category-select">Выберете категорию</label>
                    <select id="category" class="form-control">
                        <option value="web">Web project</option>
                        <option value="games">Game project</option>
                        <option value="scripts">Script</option> 
                        <option value="another">Another</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="date" class="data-select">Дата начала проекта</label>
                    <input type="date" class="form-control" name="date">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary create-button" value="Начать работу">
                </div>
            </form>
        </div>
    </div>

    {% endblock %}

</body>
</html>

diarytask/templates/create.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Создание нового проекта{% endblock %}</title>
</head>
<body>
    
    {% block form_create %}
    
    <div class="section">
        <div class="container">
            <div class="row main_create">
                <div class="col-lg-6 offset-lg-3">
                    <form action="{% url 'tasks:create_new_project' %}" method="POST">
                        {% csrf_token %}
                            {{form.as_p}}
                            <!-- 
                                <div class="form-group">
                            <label for="title" class="title-text">Введите название проекта</label>
                            <input type="text" class="form-control" id="title" name="title">
                        </div>
                        <div class="form-group">
                            <label for="category" class="category-select">Выберете категорию</label>
                            <select id="category" class="form-control" name="category">
                                <option value="Web Project">Web project</option>
                                <option value="games">Game project</option>
                                <option value="scripts">Script</option> 
                                <option value="Another">Another</option>
                            </select>
                        </div>
                        <div class="form-group" id="project-task">
                            <div class="form-group deflaut-input" id="deflaut-input">
                                <input name="task" type="text" class="form-control task-poly" placeholder="Техническое задание">
                            </div>
                        </div>
                        <div class="add-task">
                            <button type="button" class="btn btn-primary add-task" id="add-task">Добавить задание</button>
                        </div>
                             -->
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary create-button" value="Начать работу">
                        </div>
                    </form>
                    
                </div>
            </div>
        
        </div>
    </div>
    {% endblock %}

</body>
</html>

diarytask/templates/detail.html
{% extends 'base.html' %}


{% block title %}
    {{ projects.title }}
{% endblock %}

{% block project_create %}

    <div class="section main-section">
        <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        {{projects.task}}
                        <!-- 
                            <form action="" method="POST" class="add-task" >
                            {% csrf_token %}
                            
                            <input type="text" class="form-control">
                            <input type="submit" class="btn btn-primary create-button" value="Сохранить">
                        </form>
                         -->
                    </div>
                    <div class="col-lg-4 main-info">
                        <div class="project-info">
                            <h5 class="project-title">{{projects.title}}</h5>
                            <p>Категория: {{projects.category}}</p>
                            <p>Используемый язык: {{projects.language}}</p>
                            <p>Дата создания: {{projects.pub_date}}</p>
                            {% if projects.upload %}
                            Файл проекта: <a href="{{projects.upload.url}}">{{projects.upload}}</a>
                            {% endif %}
                        </div>
                        
                        <form enctype="multipart/form-data" action="{% url 'tasks:detail' project.pk %}" method="POST">
                            {% csrf_token %}
                            
                            <!-- <div class="form-group upload">
                              <label>Загрузить проект</label>
                              <input type="file" class="form-control-file" >
                            </div> -->
                            
                            <div class="fileform">
                                {{form.as_p}}
                            </div>
                            <button class="btn btn-primary" type="submit">Сохранить</button>
                            
                        </form>
                    </div>
                </div>
        </div>
    </div>    

{% endblock %}

diarytask/templates/games.html
{% extends 'base.html' %}

{% block title %}
    Game projects
{% endblock %}

{% block games %}

<div class="section">
    <div class="container category-main">
        <div class="row">
            <div class="col-lg-6 offset-3 category-projects">
                <div class="text-center category-pr">
                    {% for pw in games_projects %}
                        <a href="{% url 'tasks:detail' pw.pk %}">{{pw.title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

diarytask/templates/index backup.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" href="{% static 'css/normolize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="header">
        <a class="header__back-to-home" href="/">Home</a>
        <a class="header__new-project" href="create/">Создать новый проект</a>
        <form action="" class="header__search">
            <input type="search" class="header__search-place" placeholder="Поиск проектов">
            <input type="submit" class="header__search-button" value="Найти">
        </form>
    </div>

    <span class="border"></span>

    <div class="container-main">
        <div class="left-side-bar">   
            <a class="left-side-bar__web" href="web/">Web projects</a>
            <a class="left-side-bar__game" href="games/">Game projects</a>
            <a class="left-side-bar__scripts" href="scripts/">Scripts</a>
            <a class="left-side-bar__another" href="another/">Another</a>
        </div>
        <div class="all-projects">
            {% if latest_projects_list %}
    
            {% for p in latest_projects_list %}
                <a class="all-projects__go-to-project" href="{% url 'tasks:detail' p.id %}">{{ p.title }}</a>
            {% endfor %}
    
            {% else %}
            <p>No projects are available.</p>
            {% endif %}
        </div>
    </div>

    
    

</body>
</html>

diarytask/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="section header-section">
    <div class="container container_1">
        <div class="row">
            <div class="col-lg-4">
                <a class="btn btn-primary home-button" href="{% url 'tasks:index' %}" role="button">Home</a>
            </div>
            <div class="col-lg-4">
                <a class="btn btn-primary create-button" href="{% url 'tasks:create_new_project' %}" role="button">Create new project</a>
            </div>
            <div class="col-lg-4">
                <div class="form">
                    <form action="{% url 'tasks:search' %}" class="search-form">
                        <input type="text" class="form-control search-poly" placeholder="Search" name="search">
                        <button class="btn-primary search-button" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row main_1">
            <div class="col-lg-3">
                <div class="sidebar">
                    <a class="btn btn-outline-primary link-projects" href="{% url 'tasks:web' %}">Web projects</a>
                    <a class="btn btn-outline-primary link-projects" href="{% url 'tasks:games' %}">Game projects</a>
                    <a class="btn btn-outline-primary link-projects" href="{% url 'tasks:scripts' %}">Scripts</a>
                    <a class="btn btn-outline-primary link-projects-1" href="{% url 'tasks:another' %}">Another</a>
                </div>
            </div>
            <div class="col-lg-6 projects-main">
                <div class="all-projects text-center">
                    {% if latest_projects_list %}
    
                    {% for p in latest_projects_list %}
                        <a class="all-projects__go-to-project" href="{% url 'tasks:detail' p.pk %}">{{ p.title }}</a>
                    {% endfor %}
            
                    {% else %}
                    <p class="none-projects">No projects are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>    

</body>
</html>

diarytask/templates/scripts.html
{% extends 'base.html' %}

{% block title %}
    Scripts
{% endblock %}

{% block scripts %}

<div class="section">
    <div class="container category-main">
        <div class="row">
            <div class="col-lg-6 offset-3 category-projects">
                <div class="text-center category-pr">
                    {% for pw in scripts_projects %}
                        <a href="{% url 'tasks:detail' pw.pk %}">{{pw.title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

diarytask/templates/search.html
{% extends 'base.html' %}

{% block title %}
    Search
{% endblock %}

{% block search %}

<div class="section">
    <div class="container category-main">
        <div class="row">
            <div class="col-lg-6 offset-3 category-projects">
                <div class="text-center category-pr">
                    {% if search_list %}
                    {% for projects in search_list %}
                        <a href="{% url 'tasks:detail' projects.pk %}">{{projects.title}}</a>
                    {% endfor %}
                    {% else %}
                        <p>Ничего не найдено</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

    

{% endblock %}

diarytask/templates/web.html
{% extends 'base.html' %}

{% block title %}
    Web projects
{% endblock %}

{% block web %}

<div class="section">
    <div class="container category-main">
        <div class="row">
            <div class="col-lg-6 offset-3 category-projects">
                <div class="text-center category-pr">
                    {% for pw in web_projects %}
                        <a href="{% url 'tasks:detail' pw.pk %}">{{pw.title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}